name: 'agri_dwh'
version: '1.0.0'
config-version: 2
profile: 'agri_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  agri_dwh:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

seeds:
  agri_dwh:
    +schema: silver
    commodity_mapping:
      +column_types:
        raw_name: varchar
        commodity: varchar
        name_vi: varchar
        category: varchar
