services:
  db_init:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: agri_db_init
    env_file: ../.env
    volumes:
      - ../db_init.py:/app/db_init.py
      - ../logs:/app/logs
    command: python db_init.py
    networks:
      - agri_net

  ingest:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: agri_ingest
    env_file: ../.env
    volumes:
      - ../logs:/app/logs
      - ../ingest:/app/ingest
    command: python ingest/fao_ingest.py
    networks:
      - agri_net

  fao_bronze_seed:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: agri_fao_bronze_seed
    env_file: ../.env
    volumes:
      - ../fao_bronze_seed.py:/app/fao_bronze_seed.py
      - ../logs:/app/logs
    command: python fao_bronze_seed.py
    networks:
      - agri_net

  dbt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: agri_dbt
    env_file: ../.env
    volumes:
      - ../dbt:/app/dbt
      - ../logs:/app/logs
    working_dir: /app/dbt
    command: dbt run --profiles-dir .
    networks:
      - agri_net

  ml_arima:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ml
    container_name: agri_ml_arima
    env_file: ../.env
    volumes:
      - ../ml:/app/ml
      - ../logs:/app/logs
    command: python ml/arima_baseline.py
    networks:
      - agri_net

  ml_lstm:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ml
    container_name: agri_ml_lstm
    env_file: ../.env
    volumes:
      - ../ml:/app/ml
      - ../logs:/app/logs
    command: python ml/lstm_forecast.py
    networks:
      - agri_net

  ml_predict:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ml
    container_name: agri_ml_predict
    env_file: ../.env
    volumes:
      - ../ml:/app/ml
      - ../logs:/app/logs
    command: python ml/predict.py
    networks:
      - agri_net

  ml:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ml

    container_name: agri_ml

    env_file: ../.env

    volumes:
      - ../ml:/app/ml
      - ../logs:/app/logs

    command: python ml/train.py

    networks:
      - agri_net

  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: agri_dashboard
    env_file: ../.env
    ports:
      - "8501:8501"
    volumes:
      - ../dashboard:/app/dashboard
    working_dir: /app/dashboard
    command: >
      streamlit run app.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.headless=true
      --browser.gatherUsageStats=false
    networks:
      - agri_net
    depends_on:
      - ingest

networks:
  agri_net:
    driver: bridge
